version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: bankcards-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=bankcards
      - POSTGRES_USER=bankuser
      - POSTGRES_PASSWORD=bankpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
