openapi: 3.0.3
info:
  title: Bank Cards API
  version: 0.1.0
servers:
  - url: http://localhost:8080
paths:
  /api/auth/login:
    post:
      summary: Authenticate user and obtain JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email: { type: string, format: email }
                password: { type: string }
      responses:
        "200":
          description: JWT issued
  /api/cards:
    get:
      summary: List cards (admin sees all, user sees own)
      parameters:
        - in: query
          name: page
          schema: { type: integer, minimum: 0 }
        - in: query
          name: size
          schema: { type: integer, minimum: 1, maximum: 200 }
        - in: query
          name: status
          schema: { type: string, enum: [ACTIVE, BLOCKED, EXPIRED] }
      responses:
        "200": { description: Page of cards }
    post:
      summary: Create a card (admin) or request new card (user)
      responses:
        "201": { description: Created }
  /api/cards/{id}:
    get:
      summary: Get card by id
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        "200": { description: Card }
    patch:
      summary: Change status (activate/block)
      responses:
        "200": { description: Updated }
    delete:
      summary: Delete card (admin)
      responses:
        "204": { description: Deleted }
  /api/transfers:
    post:
      summary: Transfer between own cards
      responses:
        "201": { description: Transfer created }
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
